### ISSUE TITLE
Sdk не конвертится jetifier'om при миграции на androidX

### ISSUE THREAD

**Issue by NudeCaveMan** [flussonic/flussonic-watcher-sdk-android#1]
При миграции проекта на androidX возникают проблемы. Даже если создать в Android 3.4.1 новый, чистый проект - проблема воспроизведется.

```
Exception in thread "main" java.util.regex.PatternSyntaxException: Unclosed group near index 161
android/arch/.*

# Keep methods annotated with [^/]*OnLifecycleEvent even if they seem to be unused
# (Mostly for LiveData/LifecycleBoundObserver/onStateChange()
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.accept(Unknown Source)
        at java.util.regex.Pattern.group0(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at com.android.tools.build.jetifier.core.type.TypesMap.matchOldProguardForNewTypes(TypesMap.kt:112)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardTypesMapper.tryResolveWildcardsAndRemapAndSimplify(ProGuardTypesMapper.kt:123)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardTypesMapper.replaceType(ProGuardTypesMapper.kt:84)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser.replaceTypeInClassFilter(ProGuardClassFilterParser.kt:59)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser.access$replaceTypeInClassFilter(ProGuardClassFilterParser.kt:27)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser$rewriteClassFilter$3.invoke(ProGuardClassFilterParser.kt:46)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser$rewriteClassFilter$3.invoke(ProGuardClassFilterParser.kt:27)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:277)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
        at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:523)
        at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
        at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
        at kotlin.sequences.SequencesKt___SequencesKt.joinTo(_Sequences.kt:1716)
        at kotlin.sequences.SequencesKt___SequencesKt.joinToString(_Sequences.kt:1738)
        at kotlin.sequences.SequencesKt___SequencesKt.joinToString$default(_Sequences.kt:1737)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser.rewriteClassFilter(ProGuardClassFilterParser.kt:49)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser.access$rewriteClassFilter(ProGuardClassFilterParser.kt:27)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser$replacer$1.invoke(ProGuardClassFilterParser.kt:36)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardClassFilterParser$replacer$1.invoke(ProGuardClassFilterParser.kt:27)
        at com.android.tools.build.jetifier.processor.transform.proguard.patterns.GroupsReplacer.runReplacements(GroupsReplacer.kt:51)
        at com.android.tools.build.jetifier.processor.transform.proguard.patterns.ReplacersRunner.applyReplacers(ReplacersRunner.kt:43)
        at com.android.tools.build.jetifier.processor.transform.proguard.ProGuardTransformer.runTransform(ProGuardTransformer.kt:46)
        at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:539)
        at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:53)
        at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:521)
        at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:76)
        at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:517)
        at com.android.tools.build.jetifier.processor.Processor.transform2(Processor.kt:291)
        at com.android.tools.build.jetifier.processor.Processor.transform2$default(Processor.kt:251)
        at com.android.tools.build.jetifier.standalone.Main.run(Main.kt:156)
        at com.android.tools.build.jetifier.standalone.Main$Companion.main(Main.kt:109)
        at com.android.tools.build.jetifier.standalone.Main.main(Main.kt)
```

**Comment by whalemare** [comment]
Это серьезная проблема, вы вообще поддерживаете свой проект @flussonic-bot ?

**Comment by maxlapshin** [comment]
contact support please
